### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  id: WorkflowTerminatedEventArgs
  children:
  - System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  langs:
  - csharp
  name: WorkflowTerminatedEventArgs
  nameWithType: WorkflowTerminatedEventArgs
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  type: Class
  summary: "Adja meg az adatait a <xref href=&quot;System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated&quot;> </xref> esemény."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]A munkafolyamat-példányok három módon megszüntethető: az állomás hívhatja <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>, egy <xref:System.Workflow.ComponentModel.TerminateActivity>tevékenység előfordulhat, hogy hívható meg a munkafolyamat-példány belül, vagy a munkafolyamat futásidejű motor megszüntetheti a példány nem kezelt kivétel miatt.</xref:System.Workflow.ComponentModel.TerminateActivity> </xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> Ha a munkafolyamat-példány befejeződik, a munkafolyamat futásidejű motor riasztást a <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>esemény.</xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName> A gazdagép által előfizetett ezt az eseményt eseménykezelő felvételével <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>.</xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>"
  example:
  - "The following code example demonstrates an event handler method that takes WorkflowTerminatedEventArgs as a parameter. The `OnWorkflowTerminated` method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception%2A> property get the message associated with the exception that caused the workflow to terminate.  \n  \n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \n  \n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class WorkflowTerminatedEventArgs : System.Workflow.Runtime.WorkflowEventArgs
  inheritance:
  - System.EventArgs
  - System.Workflow.Runtime.WorkflowEventArgs
  implements: []
  inheritedMembers:
  - System.Workflow.Runtime.WorkflowEventArgs.WorkflowInstance
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  id: Exception
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  langs:
  - csharp
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "Lekérdezi a kivételt, ami miatt a munkafolyamat-példány ér véget."
  remarks: "Ha a munkafolyamat-példány nem kezelt kivétel miatt megszakadt, a kivétel a nem kezelt kivétel tartalmazza.       Amikor megszakadt a munkafolyamat-példány hívásával vagy állomás <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>vagy egy <xref:System.Workflow.ComponentModel.TerminateActivity>tevékenység, kivétel tartalmaz egy <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>, amely rendelkezik a <xref:System.Exception.Message%2A>tulajdonságának beállítása a megszűnés ok leírása.</xref:System.Exception.Message%2A> </xref:System.Workflow.ComponentModel.WorkflowTerminatedException> </xref:System.Workflow.ComponentModel.TerminateActivity> </xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> Ha a gazdagép áll le a munkafolyamat-példányhoz, átadja ezt a leírást a `string` <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>.</xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> paraméter Ha a munkafolyamat-példányhoz egy <xref:System.Workflow.ComponentModel.TerminateActivity>a leírás <xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName>.</xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName> által biztosított</xref:System.Workflow.ComponentModel.TerminateActivity>      > [!NOTE] > Bár abban az esetben a egy <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>olyan esemény, amely nem egy nem kezelt kivétel miatt, a munkafolyamat futásidejű motor magában foglalja a záráshoz ok leírása a <xref:System.Exception.Message%2A>tulajdonsága egy <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>, ez nem feltétlenül throw ezt a kivételt.</xref:System.Workflow.ComponentModel.WorkflowTerminatedException> </xref:System.Exception.Message%2A> </xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>"
  example:
  - "The following code example demonstrates how you can use the Exception property to obtain information about an exception that caused a workflow to terminate. The `OnWorkflowTerminated` method takes a <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs> as a parameter. This method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the Exception property get the message associated with the exception that caused the workflow to terminate.  \n  \n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \n  \n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]"
  syntax:
    content: public Exception Exception { get; }
    return:
      type: System.Exception
      description: "A <xref:System.Exception>, amelyek oka, hogy a munkafolyamat-példány megszakítandó.</xref:System.Exception>"
  overload: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Workflow.Runtime.WorkflowEventArgs
  isExternal: false
  name: System.Workflow.Runtime.WorkflowEventArgs
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  isExternal: false
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  isExternal: false
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
