### YamlMime:ManagedReference
items:
- uid: System.ApplicationException
  id: ApplicationException
  children:
  - System.ApplicationException.#ctor
  - System.ApplicationException.#ctor(System.String)
  - System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.ApplicationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ApplicationException
  nameWithType: ApplicationException
  fullName: System.ApplicationException
  type: Class
  summary: "Az alkalmazás által meghatározott kivételek alaposztály funkcionál."
  remarks: >-
    > [!IMPORTANT]

    >  You should derive custom exceptions from the <xref:System.Exception> class rather than the ApplicationException class.  You should not throw an ApplicationException exception in your code, and you should not catch an ApplicationException exception unless you intend to re-throw the original exception.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class ApplicationException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor
  id: '#ctor'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException()
  nameWithType: ApplicationException.ApplicationException()
  fullName: System.ApplicationException.ApplicationException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ApplicationException&quot;> </xref> osztály."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message%2A>tulajdonság az új példány egy rendszer által megadott üzenetet, amely leírja a hibát, például a &quot;Alkalmazáshiba történt.&quot;</xref:System.Exception.Message%2A> Ez az üzenet figyelembe veszi a rendszer jelenlegi kulturális környezethez.       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.ApplicationException>.</xref:System.ApplicationException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | <xref:System.Exception.Message%2A>| Az üzenet honosított hibakarakterlánc. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ApplicationException ();
    parameters: []
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException(String)
  nameWithType: ApplicationException.ApplicationException(String)
  fullName: System.ApplicationException.ApplicationException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ApplicationException&quot;> </xref> osztály egy adott hiba miatt."
  remarks: "A tartalmát a `message` paraméter az célja, hogy ember által is értelmezhető. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított.       Ez az üzenet figyelembe veszi a rendszer jelenlegi kulturális környezethez.       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.ApplicationException>.</xref:System.ApplicationException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | `Message`| A üzenetet hiba karakterlánca. |}</xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ApplicationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Egy üzenet, amely leírja a hibát."
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException(SerializationInfo,StreamingContext)
  nameWithType: ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
  fullName: System.ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ApplicationException&quot;> </xref> a szerializált adatok osztályt."
  remarks: "Ez a konstruktor nevezik meglévő kölcsönökre az adatfolyam továbbított kivétel objektum deszerializálása közben. További információkért lásd: [XML és a SOAP-szerializálási](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: protected ApplicationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException(String,Exception)
  nameWithType: ApplicationException.ApplicationException(String,Exception)
  fullName: System.ApplicationException.ApplicationException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ApplicationException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  remarks: "A tartalmát a `message` paraméter az célja, hogy ember által is értelmezhető. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított.       Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmaznia kell egy hivatkozást az előző kivétel az a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> A <xref:System.Exception.InnerException%2A>tulajdonság ugyanazt az értéket, ha átad a konstruktorban, vagy null hivatkozást ad vissza a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső kivétel értékét a konstruktor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.ApplicationException>.</xref:System.ApplicationException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A belső kivétel referencia. |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ApplicationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
    - id: innerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `innerException` paraméter nem egy null hivatkozás, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.ApplicationException.#ctor
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException()
  nameWithType: ApplicationException.ApplicationException()
  fullName: System.ApplicationException.ApplicationException()
- uid: System.ApplicationException.#ctor(System.String)
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException(String)
  nameWithType: ApplicationException.ApplicationException(String)
  fullName: System.ApplicationException.ApplicationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException(SerializationInfo,StreamingContext)
  nameWithType: ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
  fullName: System.ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.ApplicationException.#ctor(System.String,System.Exception)
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException(String,Exception)
  nameWithType: ApplicationException.ApplicationException(String,Exception)
  fullName: System.ApplicationException.ApplicationException(String,Exception)
- uid: System.ApplicationException.#ctor*
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException
  nameWithType: ApplicationException.ApplicationException
