### YamlMime:ManagedReference
items:
- uid: System.Runtime.Remoting.ServerException
  id: ServerException
  children:
  - System.Runtime.Remoting.ServerException.#ctor
  - System.Runtime.Remoting.ServerException.#ctor(System.String)
  - System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ServerException
  nameWithType: ServerException
  fullName: System.Runtime.Remoting.ServerException
  type: Class
  summary: "A kivétel történt hibák kommunikációhoz az ügyfélnek, amikor az ügyfél csatlakozik a .NET Framework alkalmazások, amelyek kivételek nem vethető el."
  remarks: "ServerException használja a HRESULT COR_E_SERVER, amely 0x8013150E értékkel rendelkezik.       Az alapértelmezett értéket használja, ServerException <xref:System.Object.Equals%2A>megvalósítása, amely támogatja a hivatkozási egyenlőség.</xref:System.Object.Equals%2A>       A kezdeti tulajdonságértékek ServerException példányt listájáért lásd: a ServerException konstruktor."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class ServerException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Remoting.ServerException.#ctor
  id: '#ctor'
  parent: System.Runtime.Remoting.ServerException
  langs:
  - csharp
  name: ServerException()
  nameWithType: ServerException.ServerException()
  fullName: System.Runtime.Remoting.ServerException.ServerException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Runtime.Remoting.ServerException&quot;> </xref> osztály alapértelmezett tulajdonságokkal."
  remarks: "<xref:System.Runtime.Remoting.ServerException>a <xref:System.SystemException>osztálytól</xref:System.SystemException> örököl</xref:System.Runtime.Remoting.ServerException> Az alábbi táblázat a kezdeti tulajdonságértékek a <xref:System.Runtime.Remoting.ServerException>osztály egy példányát: |} Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| Az üres karakterlánc (&quot;&quot;) |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.ServerException>"
  syntax:
    content: public ServerException ();
    parameters: []
  overload: System.Runtime.Remoting.ServerException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.ServerException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Remoting.ServerException
  langs:
  - csharp
  name: ServerException(String)
  nameWithType: ServerException.ServerException(String)
  fullName: System.Runtime.Remoting.ServerException.ServerException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Runtime.Remoting.ServerException&quot;> </xref> a megadott üzenet osztályt."
  remarks: "<xref:System.Runtime.Remoting.ServerException>a <xref:System.SystemException>osztálytól</xref:System.SystemException> örököl</xref:System.Runtime.Remoting.ServerException> Az alábbi táblázat a kezdeti tulajdonságértékek a <xref:System.Runtime.Remoting.ServerException>osztály egy példányát: |} Tulajdonság típus |} Az állapot |}   |-------------------|---------------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| A `message` karakterlánc |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.ServerException>"
  syntax:
    content: public ServerException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Az üzenet, amely leírja a kivétel"
  overload: System.Runtime.Remoting.ServerException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.Remoting.ServerException
  langs:
  - csharp
  name: ServerException(String,Exception)
  nameWithType: ServerException.ServerException(String,Exception)
  fullName: System.Runtime.Remoting.ServerException.ServerException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Runtime.Remoting.ServerException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  remarks: "Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmaznia kell egy hivatkozást az előző kivétel az a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> A <xref:System.Exception.InnerException%2A>tulajdonság a konstruktornak átadott ugyanazt az értéket adja vissza vagy `null` Ha a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső kivétel értékét a konstruktor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek a <xref:System.Runtime.Remoting.ServerException>osztály egy példányát: |} Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A belső kivétel referencia |}   | <xref:System.Exception.Message%2A>| A hiba karakterlánca. üzenet |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.ServerException>"
  syntax:
    content: public ServerException (string message, Exception InnerException);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
    - id: InnerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `InnerException` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokkot, amely kezeli a belső kivételben találhatók."
  overload: System.Runtime.Remoting.ServerException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.Runtime.Remoting.ServerException.#ctor
  parent: System.Runtime.Remoting.ServerException
  isExternal: false
  name: ServerException()
  nameWithType: ServerException.ServerException()
  fullName: System.Runtime.Remoting.ServerException.ServerException()
- uid: System.Runtime.Remoting.ServerException.#ctor(System.String)
  parent: System.Runtime.Remoting.ServerException
  isExternal: false
  name: ServerException(String)
  nameWithType: ServerException.ServerException(String)
  fullName: System.Runtime.Remoting.ServerException.ServerException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)
  parent: System.Runtime.Remoting.ServerException
  isExternal: false
  name: ServerException(String,Exception)
  nameWithType: ServerException.ServerException(String,Exception)
  fullName: System.Runtime.Remoting.ServerException.ServerException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.Remoting.ServerException.#ctor*
  parent: System.Runtime.Remoting.ServerException
  isExternal: false
  name: ServerException
  nameWithType: ServerException.ServerException
