### YamlMime:ManagedReference
items:
- uid: System.StackOverflowException
  id: StackOverflowException
  children:
  - System.StackOverflowException.#ctor
  - System.StackOverflowException.#ctor(System.String)
  - System.StackOverflowException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: StackOverflowException
  nameWithType: StackOverflowException
  fullName: System.StackOverflowException
  type: Class
  summary: "A kivétel fordul elő, amikor a végrehajtási verem túlcsordult, mert túl sok beágyazott metódushívások tartalmaz. Ez az osztály nem örökölhető."
  remarks: "StackOverflowException a végrehajtási verem túlcsordulási hibákat, általában nagyon részletes vagy unbounded rekurzió esetén fordul elő.       StackOverflowException használja a HRESULT COR_E_STACKOVERFLOW, amely 0x800703E9 értékkel rendelkezik. A <xref:System.Reflection.Emit.OpCodes.Localloc>köztes nyelv (IL) utasítás jelez StackOverflowException.</xref:System.Reflection.Emit.OpCodes.Localloc> A kezdeti tulajdonságértékek StackOverflowException objektum listájáért lásd: a <xref:System.StackOverflowException.%23ctor%2A>konstruktorok.</xref:System.StackOverflowException.%23ctor%2A>      ## A .NET-keretrendszer 1.0 és 1.1-es verzió szempontjai című sikerült tényleges egy StackOverflowException objektum (például unbounded rekurzió helyreállítás). A .NET-keretrendszer 2.0-s verziótól kezdődően a StackOverflowException rendelkező objektum nem catch egy `try` / `catch` letiltják, és a megfelelő folyamat befejeződik, alapértelmezés szerint. Következésképpen kell írnia a kódot felderítésére és megelőzésére veremtúlcsordulás. Például ha az alkalmazás rekurzió függ, a számláló vagy segítségével állapot feltétel a rekurzív hurok leáll. Az alábbi példában egy számláló győződjön meg arról, hogy a rekurzív hívások száma a `Execute` metódus nem haladhatja meg a MAX_RECURSIVE_CALLS állandó határozzák meg.       [!code-vb[System.StackOverflowException.Class#1](~/add/codesnippet/visualbasic/t-system.stackoverflowex_1.vb)][!code-cs[System.StackOverflowException.Class#1](~/add/codesnippet/csharp/t-system.stackoverflowex_1.cs) ]       >  [!NOTE] > Applying a <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>jelez a StackOverflowException metódusra attribútum nincs hatása.</xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>   Még mindig nem tudja kezelni a felhasználói kódból kivétel.       Ha az alkalmazás a közös nyelvi futtatókörnyezet (CLR) üzemeltet, az egyiket határozhatja meg, hogy a közös nyelvi Futtatókörnyezet kell eltávolítani a memóriából a alkalmazástartományt, amelyben a verem túlcsordulásos kivétel következik be, és továbbra is a megfelelő folyamat segítségével. További információkért lásd: [ICLRPolicyManager felület](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class StackOverflowException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor
  id: '#ctor'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.StackOverflowException&quot;> </xref> osztály, a <xref:System.Exception.Message*>tulajdonság az új példány egy rendszer által megadott üzenetet, amely leírja a hibát, például &quot;a kért művelet veremtúlcsordulást okozott.&quot;</xref:System.Exception.Message*> Ez az üzenet figyelembe veszi a rendszer jelenlegi kulturális környezethez."
  remarks: "Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.StackOverflowException>.</xref:System.StackOverflowException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Az üzenet honosított hibakarakterlánc. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException ();
    parameters: []
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.StackOverflowException&quot;> </xref> osztály egy adott hiba miatt."
  remarks: "Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.StackOverflowException>.</xref:System.StackOverflowException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String>, amely leírja a hibát.</xref:System.String> Az üzenet tartalma olyan emberek értelmezni. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.StackOverflowException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  remarks: "Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmazhat egy hivatkozást az előző kivétel a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> A <xref:System.Exception.InnerException%2A>tulajdonság, amely a konstruktorban, vagy egy null hivatkozás át ugyanazon értékét adja vissza (`Nothing` a Visual Basic nyelvben) Ha a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső kivétel értékét a konstruktor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.StackOverflowException>.</xref:System.StackOverflowException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A belső kivétel referencia. |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
    - id: innerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `innerException` paraméter nem egy null hivatkozás (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> a Visual Basic nyelvben), a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.StackOverflowException.#ctor
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
- uid: System.StackOverflowException.#ctor(System.String)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.StackOverflowException.#ctor*
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException
  nameWithType: StackOverflowException.StackOverflowException
